// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/user/service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_user_service_proto protoreflect.FileDescriptor

const file_proto_user_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/user/service.proto\x12\x04user\x1a proto/user/type/user_block.proto2]\n" +
	"\vUserService\x12N\n" +
	"\x0eCheckUserBlock\x12\x1c.user.type.CheckUserBlockReq\x1a\x1c.user.type.CheckUserBlockRes\"\x00B1Z/github.com/dwi-prasetiyo/protobuf/protogen/userb\x06proto3"

var file_proto_user_service_proto_goTypes = []any{
	(*CheckUserBlockReq)(nil), // 0: user.type.CheckUserBlockReq
	(*CheckUserBlockRes)(nil), // 1: user.type.CheckUserBlockRes
}
var file_proto_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.CheckUserBlock:input_type -> user.type.CheckUserBlockReq
	1, // 1: user.UserService.CheckUserBlock:output_type -> user.type.CheckUserBlockRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_service_proto_init() }
func file_proto_user_service_proto_init() {
	if File_proto_user_service_proto != nil {
		return
	}
	file_proto_user_type_user_block_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_service_proto_rawDesc), len(file_proto_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_service_proto_goTypes,
		DependencyIndexes: file_proto_user_service_proto_depIdxs,
	}.Build()
	File_proto_user_service_proto = out.File
	file_proto_user_service_proto_goTypes = nil
	file_proto_user_service_proto_depIdxs = nil
}
