// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/user/type/user_block.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckUserBlockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,json=user_id,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserBlockReq) Reset() {
	*x = CheckUserBlockReq{}
	mi := &file_proto_user_type_user_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserBlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserBlockReq) ProtoMessage() {}

func (x *CheckUserBlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserBlockReq.ProtoReflect.Descriptor instead.
func (*CheckUserBlockReq) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_block_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUserBlockReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckUserBlockRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBlocked     bool                   `protobuf:"varint,1,opt,name=isBlocked,json=is_blocked,proto3" json:"isBlocked,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserBlockRes) Reset() {
	*x = CheckUserBlockRes{}
	mi := &file_proto_user_type_user_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserBlockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserBlockRes) ProtoMessage() {}

func (x *CheckUserBlockRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserBlockRes.ProtoReflect.Descriptor instead.
func (*CheckUserBlockRes) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_block_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUserBlockRes) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *CheckUserBlockRes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_user_type_user_block_proto protoreflect.FileDescriptor

const file_proto_user_type_user_block_proto_rawDesc = "" +
	"\n" +
	" proto/user/type/user_block.proto\x12\tuser.type\",\n" +
	"\x11CheckUserBlockReq\x12\x17\n" +
	"\x06userId\x18\x01 \x01(\tR\auser_id\"J\n" +
	"\x11CheckUserBlockRes\x12\x1d\n" +
	"\tisBlocked\x18\x01 \x01(\bR\n" +
	"is_blocked\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB1Z/github.com/dwi-prasetiyo/protobuf/protogen/userb\x06proto3"

var (
	file_proto_user_type_user_block_proto_rawDescOnce sync.Once
	file_proto_user_type_user_block_proto_rawDescData []byte
)

func file_proto_user_type_user_block_proto_rawDescGZIP() []byte {
	file_proto_user_type_user_block_proto_rawDescOnce.Do(func() {
		file_proto_user_type_user_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_type_user_block_proto_rawDesc), len(file_proto_user_type_user_block_proto_rawDesc)))
	})
	return file_proto_user_type_user_block_proto_rawDescData
}

var file_proto_user_type_user_block_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_type_user_block_proto_goTypes = []any{
	(*CheckUserBlockReq)(nil), // 0: user.type.CheckUserBlockReq
	(*CheckUserBlockRes)(nil), // 1: user.type.CheckUserBlockRes
}
var file_proto_user_type_user_block_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_type_user_block_proto_init() }
func file_proto_user_type_user_block_proto_init() {
	if File_proto_user_type_user_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_type_user_block_proto_rawDesc), len(file_proto_user_type_user_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_type_user_block_proto_goTypes,
		DependencyIndexes: file_proto_user_type_user_block_proto_depIdxs,
		MessageInfos:      file_proto_user_type_user_block_proto_msgTypes,
	}.Build()
	File_proto_user_type_user_block_proto = out.File
	file_proto_user_type_user_block_proto_goTypes = nil
	file_proto_user_type_user_block_proto_depIdxs = nil
}
